import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { AI } from "./AI-UI-states/with-action/actions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AI>
      <html lang="en">
        <body className={inter.className}>
          <Link
            href={"/"}
            className={"text-white w-full flex justify-center py-10 text-xl"}
          >
            {"HOME"}
          </Link>
          {children}
        </body>
      </html>
    </AI>
  );
}
